version: "3"

services:
  gateway:
    build:
      context: ./gateway
    restart: always
    ports:
      - 80:80
    depends_on:
      - authentication
      - matching
      - battle

  authentication:
    image: phjppo0918/party-run-authentication
    container_name: authentication
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - redis
      
  matching:
    image: phjppo0918/party-run-matching
    container_name: matching
    restart: always
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - redis

  battle:
    image: phjppo0918/party-run-battle
    container_name: battle
    restart: always
    env_file:
      - .env
    ports:
      - 8082:8080

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
