version: "3"

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - authentication
      - matching
      - battle
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"  

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  authentication:
    image: phjppo0918/party-run-authentication:latest
    container_name: authentication
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - redis
      
  matching:
    image: phjppo0918/party-run-matching:latest
    container_name: matching
    restart: always
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - redis

  battle:
    image: phjppo0918/party-run-battle:latest
    container_name: battle
    restart: always
    env_file:
      - .env
    ports:
      - 8082:8080

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
